Status command
otter-computer/GaymersBot pull request #156
Opened 2016-12-22 13:33 UTC by ThomasShaped

Adds the `!Status`command.
- Displays the time the bot was deployed
- Shows the latest commit
- Has a link to the commit page on GitHub
- Only useable by members with the `Bot Developer` role

2016-12-22 14:15 UTC, chrislennon commented
👍 
Reference #146 - using [option 1](https://github.com/gaymers-discord/DiscoBot/issues/146#issuecomment-268479040) seems to be working after commits have taken place.

2016-12-22 20:10 UTC, brandon-a approved these changes

2016-12-23 03:24 UTC, jmariondev requested changes
Maybe wrap on 80 with this code?

Also, it would be good to integrate #157 into this so the command can only be used in the bot dev room.

Other than that, LGTM.

2016-12-23 03:24 UTC, LuaMilkshake commented on commands/status.js
> +      'https://github.com/gaymers-discord/DiscoBot/commit/' + process.env.HEROKU_SLUG_COMMIT + '\n' +
Maybe wrap on 80 here?

2016-12-24 11:53 UTC, ThomasShaped commented
- Added onlyIn prop
- Truncated message lines to 80 (ish, I did this on github web editor don't hurt me)

2016-12-24 22:10 UTC, jmariondev approved these changes

2017-01-02 09:33 UTC, merged