Embed fixes
otter-computer/GaymersBot pull request #165
Opened 2017-01-05 11:44 UTC by ThomasShaped

- Fixes some detection logic in the nickname change event that was accidentally left enabled, it should work properly now.
- Changes the URL that deleted messages event uses to render attachments. This should mean we can _likely always_ see deleted selfies uploaded directly

2017-01-06 12:53 UTC, ThomasShaped commented on commands/joined.js
> +        embed.setTitle(member.displayName.toUpperCase() +
Why did I do that

2017-01-07 02:02 UTC, jmariondev requested changes
Alright, I added my comments 😄

2017-01-07 02:02 UTC, LuaMilkshake commented on events/memberUpdated.js
> +  let embedDate = new Date(Date.now());
Why not remove this line and just add it to the below line?

2017-01-07 02:02 UTC, LuaMilkshake commented on events/memberUpdated.js
> +  embed.setTimestamp(embedDate.toISOString());
Is there a reason this is `toISOString()` here, but only supplying a `Date` object above?

2017-01-07 02:02 UTC, LuaMilkshake commented on events/memberUpdated.js
> +  // User adds a nicknameUser changed account username
o.0

2017-01-07 02:02 UTC, LuaMilkshake commented on events/memberUpdated.js
> +    }
Is this indentation change a deliberate style choice?

2017-01-07 13:11 UTC, ThomasShaped commented on events/memberUpdated.js
> +  embed.setTimestamp(embedDate.toISOString());
No! 😄

I mean the `toISOString` is required as discord fucking *dies* if you give it _anything else_ in that embed slot, but I don't know why I didn't just `Date.now().toISOString()` and skipped the date variable.

2017-01-07 13:12 UTC, ThomasShaped commented on events/memberUpdated.js
> +    }
ESlint gave me indentation squiglies about the formatting here.

2017-01-07 13:44 UTC, ThomasShaped commented on events/memberUpdated.js
> +  // User adds a nicknameUser changed account username
>_>;

2017-01-07 13:51 UTC, otter-computer reviewed
Updated your requested changes @LuaMilkshake 😁😁😁

2017-01-10 10:33 UTC, merged