Add !roles command to list available roles
otter-computer/GaymersBot pull request #176
Opened 2017-01-30 10:37 UTC by ThomasShaped

- Adds the `roles` command to list roles that people can add to themselves
- Updates the usage help of the `!role` command to include information about this

2017-01-30 10:38 UTC, ThomasShaped commented
Closes #101

2017-01-31 01:24 UTC, brandon-a approved these changes

2017-01-31 02:29 UTC, jmariondev requested changes
This is indeed a needed feature! I made a change to your loop logic to simplify it, see the branch linked below (it's based on this PR commit, you can just merge it) for those changes. Other than that, this looks 👌 

https://github.com/LuaMilkshake/DiscoBot/tree/role-list

2017-01-31 08:33 UTC, ThomasShaped commented
GJ much cleaner, will close this and merge your version.

2017-01-31 09:15 UTC, merged