Add !roles reminder to !set18 for 'Under 18'
otter-computer/GaymersBot pull request #272
Opened 2017-05-20 23:50 UTC by LuaMilkshake

When a user with 'Under 18' runs the !set18 command, this will also remind them of the !roles command.

2017-05-21 02:18 UTC, LuaMilkshake commented
^^ Updated for your new message @brandon-a

2017-05-24 22:43 UTC, otter-computer requested changes

2017-05-24 22:43 UTC, ThomasShaped commented on commands/set18.js
> +          'Check out `!roles` to see what I *can* add! :smile:');
Should be `!role`

2017-05-24 23:31 UTC, otter-computer approved these changes

2017-06-14 17:55 UTC, merged

2017-06-14 18:27 UTC, LuaMilkshake commented on commands/set18.js
> +          'Check out `!roles` to see what I *can* add! :smile:');
I'm dumb. I'm the one that made that change...