Initial steps for minecraft user registration
otter-computer/GaymersBot pull request #306
Opened 2017-06-24 11:56 UTC by chrislennon

Provides a mechanism to allow for user registration to minecraft server when it doesnt match their discord name, allowing us to keep track of who is who.

relates to https://github.com/gaymers-discord/administration/issues/14

built on minecraft api stack at https://github.com/gaymers-discord/gaymers-minecraft-api

Does:
- checks if a user is registered
- registration of user to database
- deregistration of user from database

To-do:
- processing the result of registration towards actual server whitelisting making use of the [rcon stack](https://github.com/gaymers-discord/server-rcon)

2017-06-24 15:36 UTC, chrislennon commented
Ready for review.
Only component missing now is a Minecraft server 😜

2017-06-24 23:34 UTC, chrislennon commented
![ezgif com-resize](https://user-images.githubusercontent.com/9197696/27512599-59c3272e-5946-11e7-8438-98176274fded.gif)

Soon™

2017-06-26 16:51 UTC, chrislennon commented
- [x] (De)Registration of Discord username against Minecraft username
- [x] Functionality for Admin/Mods to kick & (ub)ban users
- [x] User level whois command
- [x] 2 way chat mirroring
- [x] Handle errors around server (or database) being offline

Will write up the commands available and seek any further suggestion on https://github.com/gaymers-discord/administration/issues/14

Issues with the code side of the request can go on this PR.

2017-06-27 19:05 UTC, chrislennon commented
Feedback from brief testing with @ThomasShaped:

- [ ] Emoji in the username needs appropriate testing
- [ ] Store the Nickname in the database for response
- [ ] Help for admin command
- [ ] Arguments for commands should be case insensitive
- [ ] Line 201 games\index.js throwing errors ` Cannot read property 'commands' of undefined`
- [ ] Alias game with games
- [ ] Alias deregister with unregister

2017-06-29 00:54 UTC, jmariondev requested changes
Does #311 help with the code duplication here as well?

2017-06-29 00:54 UTC, LuaMilkshake commented on games/rcon.js
> +  if (action == 'add') {
A switch might be cleaner here?

2017-06-29 00:54 UTC, LuaMilkshake commented on games/minecraft/admin.js
> +      if (result){
Some of this indentation can be avoided by handling 'bail-outs' differently. Instead of
```javascript
if (goodCondition) {
    if (anotherGoodCondition) {
        // Do what we're actually trying to do
    } else {
        // Fail handling 2
    }
} else {
    // Fail handling 1
}
```
this can be written as
```javascript
if (inverseGoodCondition) { // ie (!goodCondition)
    // Fail handling 1
    return;
}

if (inverseAnotherGoodCondition) {
    // Fail handling 2
    return;
}

// Do what we're actually trying to do
```

2017-06-29 00:54 UTC, LuaMilkshake commented on games/minecraft/admin.js
> +              message.channel.send(message.author + ', Sorry there was an issue processing your command :cry:. ' + data);
These lines are getting quite long.

2017-06-29 00:54 UTC, LuaMilkshake commented on games/rcon.js
> +  if (action == 'kick') {
Same note about switch.

2017-06-30 17:18 UTC, chrislennon commented on games/rcon.js
> +  if (action == 'add') {
fixed in https://github.com/gaymers-discord/DiscoBot/pull/306/commits/582709737c4c38363ec6099b2f3ddb0a013a76b6

2017-06-30 17:25 UTC, chrislennon commented on games/minecraft/admin.js
> +      if (result){
I get what you are meaning with this and I should attempt to fix some of the readability of this section, however I'm not sure the above suggestion can directly fix this. 

What is happening in this section is calls towards a variety of APIs (rcon, minecraft) which have a bit of latency in contacting the serverless functions then the database or game server. Here I'm making use of callbacks to ensure I don't process subsequent steps prior to having a result for the first.

I'll try shuffle the checks around and see if I can come up with something clearer.

2017-06-30 17:28 UTC, chrislennon commented
Regarding the comment on #311, yes that PR should save a lot of the overlap between `./games/index.js` and the utility functions that 311 brings in, if 311 hits master first I'll rewrite this code to make use of them

2017-06-30 19:03 UTC, chrislennon commented on games/minecraft/admin.js
> +              message.channel.send(message.author + ', Sorry there was an issue processing your command :cry:. ' + data);
fixed within this commit https://github.com/gaymers-discord/DiscoBot/pull/306/commits/dec7ce3f9657530a5d850087bd34922a86044e31

2017-07-11 10:40 UTC, chrislennon commented
Now handling emoji support too - there was an error in the default connection type of the [mysql driver](https://github.com/gaymers-discord/gaymers-user-functions/commit/d98e9c00d669d94fc9f8807e5f5b5f23aa46c132).

I believe this is good to move into the next stage now - either private or server wide testing.

2017-08-22 14:34 UTC, closed without merging